name: CI/CD Pipeline
on:
  push:
    branches:
      - 'wix-installer'

#  workflow_dispatch:
#  #Trigger the workflow on pull req from the prod br
#  pull_request:
#    types: [closed]
#    branches:
#      - master


jobs:
  # Build and  Deploy
  install_prerequisite:
    name: Prerequisite Install
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        #checkout code
        uses: actions/checkout@v3
        #Set up JDK 17
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install dotnet and wix311
        run: |
          curl -H "Connection: close" -o dotnet.exe https://download.visualstudio.microsoft.com/download/pr/56785524-dcd2-425a-8a95-3c2ee607b22f/e32ce2d12821f85c7d5e9cdee5ff5264/dotnet-sdk-6.0.411-win-x64.exe
          Start-Process ./dotnet.exe -ArgumentList "/S /v/qn"
          dir
          Expand-Archive -Path wix311.zip -DestinationPath .
          dir
          Start-Process ./wix311.exe -ArgumentList "/S /v/qn"
        shell: pwsh

      - name: Package Installer
        run: |
          curl -o jmods.zip https://download2.gluonhq.com/openjfx/20.0.1/openjfx-20.0.1_windows-x64_bin-jmods.zip
          Expand-Archive -Path jmods.zip -DestinationPath .
          mvn -B package -DskipTests --file pom.xml
          jpackage --verbose --type exe --input . --dest . --main-jar .\target\HelloWorldApp-1.0-SNAPSHOT.jar --main-class com.genkey.helloworldapp.HelloApplication --module-path ".\javafx-jmods-20.0.1" --add-modules javafx.controls,javafx.fxml --win-shortcut --win-menu --strip-debug --runtime-image ""

#      - name: Publish exe file to github packages
#        uses: actions/upload-artifact@v2
#        with:
#          name: HelloApplication-1.0.exe
#          path: .\HelloApplication-1.0.exe

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_FOR_EXE }}
        with:
          tag_name: v1.0.1 # Specify the desired tag name
          release_name: Release v1.0.0  # Specify the desired release name
          body: |
            Release v1.0.1
          draft: false
          prerelease: false

      - name: Attach Artifact to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_FOR_EXE }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: .\HelloApplication-1.0.exe
          asset_name: HelloApplication-1.0.exe
          asset_content_type: application/octet-stream

