name: Creating Installer with NSIS
on:
  push:
    branches:
      - 'master'


jobs:
  create_installer:
    name: Create Installer
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        #checkout code
        uses: actions/checkout@v3
        #Set up JDK 17
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Download Necessary Files for JRE
        run: |
          curl -o jmods.zip https://download2.gluonhq.com/openjfx/20.0.1/openjfx-20.0.1_windows-x64_bin-jmods.zip
          Expand-Archive -Path jmods.zip -DestinationPath .
          curl -o jmods-sdk.zip https://download2.gluonhq.com/openjfx/20.0.2/openjfx-20.0.2_windows-x64_bin-sdk.zip
          Expand-Archive -Path jmods-sdk.zip -DestinationPath .
        shell: cmd

      - name: Create JAR File
        run: |
          mvn -B package -DskipTests --file pom.xml
        shell: cmd

      - name: Create JRE
        run: |
          jlink --module-path ".\javafx-jmods-20.0.1;.\javafx-sdk-20.0.2\lib;%JAVA_HOME%\jmods" --add-modules java.base,java.desktop,java.scripting,java.xml,javafx.base,javafx.controls,javafx.graphics,javafx.media,jdk.jsobject,jdk.xml.dom,javafx.fxml --output jre-14.0.2 --strip-debug --compress 2 --no-header-files --no-man-pages
          dir
          dir jre-14.0.2
        shell: cmd
